package br.com.bms.view;

import br.com.bms.controller.CargoController;
import br.com.bms.model.Cargo;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BRUNO
 */
public class CargoGUI extends javax.swing.JDialog {

    private DefaultTableModel modelo = new DefaultTableModel();
    private int linhaSelecionada;

    public CargoGUI() {
        this.modelo = modelo;
        initComponents();

    }

    public CargoGUI(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
    }

    public CargoGUI(DefaultTableModel modelo, int linha, int id) {
        this.modelo = modelo;
        initComponents();
        this.linhaSelecionada = linha;
        CargoController fc = new CargoController();
        Cargo c = new Cargo();
        c.setId(id);
        c = fc.getCargoById(c);
        setValues(c);

    }

    public void setValues(Cargo cargo) {
        tf_id.setText(String.valueOf(cargo.getId()));
        tf_nome.setText(String.valueOf(cargo.getNome()));
        tf_descricao.setText(String.valueOf(cargo.getDescricao()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        tf_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_descricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tf_r = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BMS - CADASTRO E MANUTENÇÃO DE CARGOS  - EDIÇÃO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Cargo"));

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Cancelar");

        jLabel2.setText("Nome: ");

        tf_id.setEditable(false);

        jLabel1.setText("Id: ");

        jLabel3.setText("Descrição.:");

        tf_descricao.setColumns(20);
        tf_descricao.setRows(5);
        tf_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_descricaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tf_descricao);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Caracteres Restantes.:");

        tf_r.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_r.setText("300");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_r)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tf_nome)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar)
                        .addComponent(btCancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tf_r)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        try {

            Cargo c = new Cargo();
            CargoController cc = new CargoController();

            c.setNome(tf_nome.getText());
            c.setDescricao(tf_descricao.getText());

            //Edição
            if ((!tf_id.getText().equals("")) || (tf_id.getText().equals(null))) {

                c.setId(Integer.parseInt(tf_id.getText()));

                //cc.save(c);
                if (cc.save(c) != null) {
                    modelo.removeRow(linhaSelecionada);
                    System.out.println(modelo.getRowCount());
                    modelo.addRow(new Object[]{c.getId(), c.getNome(), c.getDescricao()});
                    System.out.println(modelo.getRowCount());
                    System.out.println("Devia ter adicionado");
                    this.dispose();
                }

            } else { //Inserção
                int id = cc.save(c).getId();
                c.setId(id);
                System.out.println(
                        c.getId() + "\n "
                        + c.getNome() + "\n "
                        + c.getDescricao()
                );

                System.out.println(modelo.getRowCount());
                modelo.addRow(new Object[]{c.getId(), c.getNome(), c.getDescricao()});
                System.out.println(modelo.getRowCount());
                this.dispose();
            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar", "FATAL ERROR!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void tf_descricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_descricaoKeyReleased
        int c_r = tf_descricao.getText().length();
        tf_r.setText(String.valueOf(300 - c_r));
        if (300 - tf_descricao.getText().length() < 0) {
            btSalvar.setEnabled(false);
        } else {
            btSalvar.setEnabled(true);
        }

    }//GEN-LAST:event_tf_descricaoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tf_descricao;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JLabel tf_r;
    // End of variables declaration//GEN-END:variables
}
