package br.com.bms.view;

import br.com.bms.controller.CargoController;
import br.com.bms.model.Cargo;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BRUNO
 */
public class ListarCargosGUI extends javax.swing.JDialog {

    /**
     * Creates new form CargoGUI
     */
    private JTable tabela;
    private DefaultTableModel modelo = new DefaultTableModel();

    public ListarCargosGUI(java.awt.Frame parent, boolean modal) {
        criarTabela();
        initComponents();
        scrol.setViewportView(tabela);

    }

    public void criarTabela() {
        tabela = new JTable(modelo);
        modelo.addColumn("Id");
        modelo.addColumn("Nome");
        modelo.addColumn("Descrição");
        preencherTabela();
    }

    public void preencherTabela() {
        CargoController cc = new CargoController();
        for (Cargo c : cc.listAll()) {
            modelo.addRow(new Object[]{c.getId(), c.getNome(), c.getDescricao()});
        }
        if (modelo.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "Não existe nenhum cargo cadastrado!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JPanel();
        tf_pesquisa = new javax.swing.JTextField();
        scrol = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botao_inserir = new javax.swing.JButton();
        botao_remover = new javax.swing.JButton();
        botao_editar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BMS - MANUTENÇÃO DE CARGOS");
        setResizable(false);

        painel_principal.setBackground(new java.awt.Color(255, 255, 255));

        tf_pesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesquisaKeyReleased(evt);
            }
        });

        scrol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pesquisar");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout());

        botao_inserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_inserir.setText("Inserir");
        botao_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_inserirActionPerformed(evt);
            }
        });
        jPanel2.add(botao_inserir);

        botao_remover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_remover.setText("Remover");
        botao_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_removerActionPerformed(evt);
            }
        });
        jPanel2.add(botao_remover);

        botao_editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_editar.setText("Editar");
        botao_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_editarActionPerformed(evt);
            }
        });
        jPanel2.add(botao_editar);

        botao_sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        jPanel2.add(botao_sair);

        javax.swing.GroupLayout painel_principalLayout = new javax.swing.GroupLayout(painel_principal);
        painel_principal.setLayout(painel_principalLayout);
        painel_principalLayout.setHorizontalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 574, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painel_principalLayout.setVerticalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_removerActionPerformed

        int linhaSelecionada = tabela.getSelectedRow();
        Integer codigoCargoSelecionado = (Integer) tabela.getValueAt(linhaSelecionada, 0);
        Cargo c = new Cargo();
        c.setId(codigoCargoSelecionado);

        int resposta = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir este registro?", "", JOptionPane.YES_NO_OPTION);
        if (linhaSelecionada >= 0) {
            if (resposta == 0) {
                CargoController cc = new CargoController();
                if (cc.remove(c) == true) {
                    modelo.removeRow(linhaSelecionada);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }

    }//GEN-LAST:event_botao_removerActionPerformed

    private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
        //Passa por parâmetro no construtor o modelo da tabela        
        CargoGUI c = new CargoGUI(this.modelo);
        c.setVisible(true);
    }//GEN-LAST:event_botao_inserirActionPerformed

    private void tf_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaKeyReleased
    }//GEN-LAST:event_tf_pesquisaKeyReleased

    private void botao_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_editarActionPerformed
        //Começa de 0 -1 não existe nenhuma linha selecionada
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
       // System.exit(0);
        if (linhaSelecionada >= 0) {
            Integer codigoCargoSelecionado = (Integer) tabela.getValueAt(linhaSelecionada, 0);
        
            CargoGUI f = new CargoGUI(modelo, linhaSelecionada, codigoCargoSelecionado);
            f.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
    }//GEN-LAST:event_botao_editarActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCargosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCargosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCargosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCargosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListarCargosGUI dialog = new ListarCargosGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_editar;
    private javax.swing.JButton botao_inserir;
    private javax.swing.JButton botao_remover;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painel_principal;
    private javax.swing.JScrollPane scrol;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
